name: poc
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  go_router: ^16.1.0
  http: ^1.4.0
  loading_animation_widget: ^1.3.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  flutter_gen_runner: ^5.11.0

assets:
  - assets/test.txt

flutter:
  generate: true
  uses-material-design: true
